### ISSUE TITLE
I can't upload image from external sources

### ISSUE THREAD

**Issue by Eric-Bujeque** [Shopify/shopify_python_api#182]
I read in https://help.shopify.com/api/reference/product_image that you can specify external images with src parameter, and shopify downloads it.

> Create a new product image using a source URL that will be downloaded by Shopify
```
{
  "image": {
    "src": "http:\/\/example.com\/rails_logo.gif"
  }
}
```

When I try:
```
img = shopify.Image()
img.product_id = 1234 (valid product id)
img.src = 'http://whateverurl.com/image.gif'
img.save()
```
I get: **(image/gif, image) is not a recognized format.**

I also tried to use img.attach_image() function like:
```
import requests
r = requests.get('http://whateverurl.com/image.gif')
img.attach_image(r.content)
img.product_id = 1234 (valid)
img.save()
```
And I get: **{the b64 image} is not JSON serializable**. I didn't encode it because It is already done inside the attach_image() (Am I right?). 

Then, what is the proper way to upload images from external sources? I should say that the images I want to use is from a product provider, and I have their consent.

**Comment by Eric-Bujeque** [comment]
I fixed the second case (with attach_image()) with the solution posted in[ this issue](https://github.com/Shopify/shopify_python_api/issues/147) for python3. But I think that modify the source code is not a good idea.

**Comment by jamiemtdwyer** [comment]
Closed by https://github.com/Shopify/shopify_python_api/pull/177

**Comment by jamiemtdwyer** [comment]
Sorry, re-opening since the first issue still needs to be investigated.

**Comment by vincestus** [comment]
Hello,

I'm not able neither to upload local images to a product. I tried the following ways hereunder but this doesn't seem to work.

**First attempt**

```
image = shopify.Image({"product_id":new_product.id})
    image.position = 1
    binary_in = b64decode("R0lGODlhbgCMAPf/APbr48VySrxTO7IgKt2qmKQdJeK8lsFjROG5p/nz7Zg3MNmnd7Q1MLNVS9GId71hSJMZIuzTu4UtKbeEeakhKMl8U8WYjfr18YQaIbAf==")
    image.attach_image(data=binary_in, filename='image.png')
    image.save()
```

**second attemps**

```
    path = "./test/image.jpg"
    with open(path, "rb") as f:
        binary_in = b64encode(f.read())
        image.attach_image(data=binary_in, filename="image_file.jpg")
        image.save()
```
Neither of them works . What am I doing wrong (I tried on python 3.6 and 3.4)?

Best regar
